// src/pages/react-page/index.tsx
import { FC, useCallback, useEffect, useMemo, useState } from "react";
import "./index.less";

export const ReactPage: FC = () => {
  const [count, setCount] = useState(0);

  const doubleCount = useMemo(() => {
    return count * 2;
  }, [count]);

  const increment = useCallback(() => {
    setCount((count) => count + 1);
  }, []);

  useEffect(() => {
    console.log("useEffect called: " + count);
    return () => {
      console.log("useEffect cleanup: " + count);
    };
  }, [count]);

  return (
    <div class="react-page">
      react
      <div>{count}</div>
      <div>{doubleCount}</div>
      <button
        class={count + "1"}
        onClick={() => {
          increment();
        }}
      >
        increment
      </button>
    </div>
  );
};

// src/pages/solid-page/index.tsx
import { createSignal } from "solid-js";
import "./index.less";

export const SolidPage = () => {
  const [count, setCount] = createSignal(0);

  return (
    <div class="solid-page">
      solid
      <div>{count()}</div>
      <button
        onClick={() => {
          setCount(count() + 1);
        }}
      >
        increment
      </button>
    </div>
  );
};
